### ISSUE TITLE
Força tarefa de melhoria de qualidade

### ISSUE THREAD

**Issue by bamorim** [institutoreditus/reditus-app#71]
# Introdução

Prezados, como conversado no whatsapp, esta issue tem o objetivo de colocar de forma registrada ações que precisamos tomar para organizar melhor o nosso code base. Também é um lugar para discutirmos o que tem que melhorar.

A estrutura desta issue começará com uma todo-list que será autalizada para termos track dos efforts seguindo de alguns paragrafos explicando os problemas e as soluções propostas.

# TODO

## Ferramentas de qualidade básicas

- [ ] Atualizar readme com instruções completas para rodar todos os testes com sucesso na máquina do desenvolvedor
- [ ] Adicionar ferramenta de report de code coverage
- [ ] Adicionar CI
- [x] Adicionar Rubocop
- [ ] Corrigir erros do rubocop introduzidos depois da adoção da ferramenta
- [ ] Corrigir todas os erros legados do rubocop de acordo com o arquivo `rubocop_todo.yml`

## Arquitetura

- [ ] Isolar os serviços externos (pagar.me, hubspot, etc) para poder rodarmos as coisas de forma mais independente
- [ ] Decidir apenas um pattern de domain logic (fat models, interactor, services, etc)
- [ ] Refatorar o codigo para remover os outros patterns
- [ ] Tirar lógica dos controllers e colocar de acordo com o pattern escolhido
- [ ] Pensar e organizar futuro da arquitetura, levando em consideração ideias como:
  - Separação por bounded context (DDD)
  - Event based context interaction (com patterns como pubsub)

# Problemas

Esta seção por ora é só uma analise inicial minha (@bamorim) sobre o estado atual da aplicação e os maiores pain points. Conforme a discussão evolua, podemos adicionar mais coisas aqui. A ideia no geral é explicar porque algumas coisas como estão são ruins e por que devemos resolver.

## Onboarding de novos desenvolvedores

Quando tentei começar no projeto, não consegui simplesmente baixar, seguir o readme e ter os testes funcionando. Faltava algumas configurações que não estavam explicadas em lugar nenhum. Isso é reflexo de duas coisas:
- Falta de um README atualizado explicando setup, teste e outros detalhes de como contribuir com o projeto
- Dependencias externas muito acopladas ao código, o que faz com que seja obrigatório configurar coisas como hubspot e pagarme, dificultando o teste em isolamento do sistema
- Falta de CI para mostrar que o problema era na minha configuração mesmo, e não nos testes em si, o que tirou confiança minha no codebase para começar a codificar algo

## Qualidade e consistencia de código

Quando olhei o código, vi que a identação estava diferente em arquivos diferentes, algumas strings estavam com aspas simples, outros com aspas duplas. Isso acontece principalmente porque nào se tem uma validação de style guide. Para isso comecei adicionando rubocop, que valida e até corrige algumas ofensas automaticamente.

Mas após isso, outro problema surgiu: novas features adicionadas geraram alertas no rubocop novamente. Isso aconteceu pois não tinhamos nenhum CI in place para reportar estas ofensas a quem estava desenvolvendo, que fez com que o código chegasse a master sem estar de acordo com o padrão de qualidade configurado no rubocop. Por isso um CI é importante

## Arquitetura

Um dos principais problemas de arquitetura é o mesmo manifestado nos testes: não existe separação forte dos serviços externos, de maneira que o nosso código depende diretamente de serviços externos. Pensar em termos de Clean Architecture, Hexagonal Architecture ou similares pode ajudar. No final, quase todos estão em linha com a ideia de inversão de dependencias baseado em interfaces e adapters configuráveis.

Outro problema que percebi, é que ao longo do tempo, diversas formas de organizar código foram testadas: Interactor pattern, Organizar em service objects, deixar a lógica no controller, etc.

O que isso gera é uma incerteza de como alguem desenvolvendo um código deve prosseguir ao desenvolver uma nova funcionalidade.

Para resolver isso, primeiro precisamos decidir como queremos fazer, e as opções incluem (não somente):
- Rails Way: Fat Models, Slim Controllers + Concerns
- Uncle bob way: Interactor pattern
- Mais genérico: service (muita variação, tem muitos detalhes para decidir)

Em linhas gerais, o importante aqui é escolher uma forma, documentar bem, migrar tudo pra esse pattern. Assim, qunado alguem for desenvolver uma feature nova ou mudar uma existente, vai saber exatamente onde procurar e como fazer. Isso é o mais importante: tirar o estresse de pensar como organizar o código.

## Domain Driven Design

Um ponto que percebi, provavelmente causado por muita logica nos controllers e dependencia forte de sistemas externos, é que é dificil entender o domain. Um dos sintomas é o fato do que está em "models" ser apenas uma relação com o banco de dados. Isso é o que normalmente é chamado de "anemic domain". 
A ideia é que os domain entities não representam bem o dominio, falta funcionalidade e eles apenas representam os dados salvos. Com rails isso ainda é agravado, porque quando olhamos o codigo de um model, é tudo implicito (temos que olhar o `db/schema.rb` para entender, e este também estava desatualizado). O que isso gera é uma dificuldade de entender o que cada entidade representa no todo do sistema.

Outra coisa para se pensar também é se faz sentido separar o código em contexts separados. Isto é, o sistema toca ou provavelmente tocará em várias partes do instituto, por exemplo:

- Programa de Embaixadores
- Doações
- Gestão do fundo (reports financeiros, balanço, etc)

Além de coisas mais genéricas como IAM (login, usuario, etc), Marketing, e outros supporting domains.

Talvez faça sentido separar em caixinhas mais especificas. Isto é um trabalho grande, mas pode trazer um bom entendimento sobre o todo, mas é uma discussão mais demorada.
